name: Create loc badge

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Count lines
        uses: ./
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          directory: src
          badge: loc.svg
          badge_label: Source LoC
          badge_branch: images
